### ISSUE TITLE
Error connection

### ISSUE THREAD

**Issue by tjawolfs** [steffjenl/com.ubnt.unifiprotect#15]
since 2 days the app isn’t working and i can’t get a new connection.

this is my code:
25453864-08c0-4641-85a1-3764c019eeea

**Comment by steffjenl** [comment]
> since 2 days the app isn’t working and i can’t get a new connection.
> 
> this is my code:
> 25453864-08c0-4641-85a1-3764c019eeea

Do you have the last firmware on your cloudkey? and upgraded unifi protect to the last version?

**Comment by tjawolfs** [comment]
Cloudkey has firmware 1.1.13
Protect: 1.13.7
App: 1.2.9

**Comment by steffjenl** [comment]
> Cloudkey has firmware 1.1.13
> Protect: 1.13.7
> App: 1.2.9

Please update your cloudkey, next version we will remove the old firmware support complete.

**Comment by steffjenl** [comment]
Closed issue because no response, and this will be fixed when the cloud key is upgraded.
