### ISSUE TITLE
Can't login after update

### ISSUE THREAD

**Issue by Krisstenswe** [steffjenl/com.ubnt.unifiprotect#16]
Hi!
3 days ago I updated UCK-G2-Plus to 2.0.27 and Protect to 1.17.3.
I have a dedicated user for Homey with permissions to Protect.
App is 1.2.9.
IP adress checked and is correct. Port is 7443.
I have rebooted UCK and app several times without success.
When I now try to log in, I get "Error: Request failed: /api/auth {status code: 404) (creds: {"username":"...

**Comment by steffjenl** [comment]
Please select UnifiOs en port 443 in the application settings

**Comment by Krisstenswe** [comment]
I changed the port to 443 and the app crashed. See picture.
I then marked 'UNIFIOS (DREAM MACHINE PRO)' and it worked! Thnx!

![IMG_2147483647 (2)](https://user-images.githubusercontent.com/33200170/107126018-88e0d900-68ad-11eb-9cce-226b7c273af6.jpg)
