### ISSUE TITLE
Too many times...

### ISSUE THREAD

**Issue by iFac3** [steffjenl/com.ubnt.unifiprotect#17]
Hi Stèphan,

Since “real time” updates I experience new thing. Homey disables flows what are triggered by my G4 dome. An indoor deployed cam, It has plenty of motion alerts because the whole family activates it very often.

Never seen a notification like this below:

![F452A7DA-B041-4F09-8CA8-9505BD3D2051](https://user-images.githubusercontent.com/51527573/107150192-f1d35a00-695c-11eb-9b8f-b8a8d05e1a17.jpeg)

**Comment by iFac3** [comment]
...funny part is “Alarm - Living room camera” is a flow which has “And” conditions so were  not executed anytime because we were at home the whole weekend.

https://homey.app/f/HTa0Zt

**Comment by steffjenl** [comment]
That is strange, real-time updates sends an montion event to Homey when there is an motion on the camera. The old version was reading the events page from protect and triggered an motion event when there was a new event.

Maybe is Protect seeing many motion events as one event? you can look this on the event page within Protect.

**Comment by denniedegroot** [comment]
I have the same issue. It seems the protect websocket keeps sending motion events if something is moving.

**Comment by steffjenl** [comment]
> I have the same issue. It seems the protect websocket keeps sending motion events if something is moving.

That is the correct way, can you try to switch the flow? when the alarm is of then trigger the flow?

**Comment by denniedegroot** [comment]
> > I have the same issue. It seems the protect websocket keeps sending motion events if something is moving.
> 
> That is the correct way, can you try to switch the flow? when the alarm is of then trigger the flow?

I have a timeout set in the flow. But the error remains and the flow will be disabled. I think we need a timeout on triggering the flow.

**Comment by denniedegroot** [comment]
Hmm I think it is something different. Over time the websocket seems to be getting a LOT more messages. It looks like there are multiple connections to the real-time engine.

If the app just started you only receive 1 message (pong?) per second, after the app is running for a day it is more like 10 messages (pong?) per second.

**Comment by steffjenl** [comment]
> Hmm I think it is something different. Over time the websocket seems to be getting a LOT more messages. It looks like there are multiple connections to the real-time engine.
> 
> If the app just started you only receive 1 message (pong?) per second, after the app is running for a day it is more like 10 messages (pong?) per second.

Strange, maybe the reconnect function, tomorrow i will run the application in debug mode to see what is happening

**Comment by steffjenl** [comment]
I have moved the websocket client from the driver to the application class. Maybe this will help? On my own Homey i don't see this issue. 

https://homey.app/a/com.ubnt.unifiprotect/test/

**Comment by iFac3** [comment]
Test in progress!

Üdv,

G.

**Comment by steffjenl** [comment]
> Test in progress! Üdv, G.
> […](#)
> On 2021. Feb 13. 17:22 +0100, steffjenl ***@***.***>, wrote: I have moved the websocket client from the driver to the application class. Maybe this will help? On my own Homey i don't see this issue. https://homey.app/a/com.ubnt.unifiprotect/test/ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

Know i see the problem i think, after some hours i getting also lots of new messages.

**Comment by iFac3** [comment]
Issue still exists in current version.

![29C0B799-12F3-421E-BF4C-815C414ADA62](https://user-images.githubusercontent.com/51527573/108112505-7b3e0700-7096-11eb-87e3-aede016a4d60.jpeg)

**Comment by iFac3** [comment]
App was disabled without any notification.

 
![IMG_0761](https://user-images.githubusercontent.com/51527573/108586899-6c36ad80-7351-11eb-9ba9-154cfa18f755.jpeg)


Should not be restored the earlier version as stable?

**Comment by steffjenl** [comment]
With support from @denniedegroot i have rewritten the application and removed old code. Information about the camera is updated from realtime services and fixed the bug #17 and #20. @iFac3 can you try the new version?

https://homey.app/a/com.ubnt.unifiprotect/test/

**Comment by iFac3** [comment]
Of course! Install in progress!

Rgds,

Gergely.

**Comment by denniedegroot** [comment]
I have the latest version running for a day now, for me it works great now.

**Comment by mbnn** [comment]
Heerlijk thx voor de update, zo te zien werkt de flow nu ook prima met de deurbel van de G4 deurbel :) Thx!

**Comment by steffjenl** [comment]
Ik sluit hierbij de issue, de nieuwe versie is live!
