### ISSUE TITLE
Doorbell not always ringing

### ISSUE THREAD

**Issue by denniedegroot** [steffjenl/com.ubnt.unifiprotect#18]
The G4 doorbell is not always triggering. This is due to the following line:
https://github.com/steffjenl/com.ubnt.unifiprotect/blob/c2b554b7c36eb9036d3890c0e6a31983c8dcf8c0/lib/websocket.js#L210

A payload can contain both a lastMotion and lastRing object. So the "return" needs to be deleted.

**Comment by steffjenl** [comment]
Next version this wil be removed!

**Comment by steffjenl** [comment]
@denniedegroot is payload.isMotionDetected also filled ?

**Comment by denniedegroot** [comment]
@steffjenl Yes. 

```
{
  lastMotion: 1612883092648,
  isMotionDetected: true,
  lastRing: 1612883093292
}
```

**Comment by denniedegroot** [comment]
Works good, thanks!
