### ISSUE TITLE
Debugging via settings possible Homey problem

### ISSUE THREAD

**Issue by denniedegroot** [steffjenl/com.ubnt.unifiprotect#19]
I see that you added debugging messages via the 'Settings.set' API of Homey.
This is probably not a good idea because settings are saved to the EMMC flash memory.
This can cause many write cycles and **significantly** reduce the lifetime of Homey.

Note that as Athom doesn't share details of when settings are saved to the EMMC this is an assumption.

**Comment by steffjenl** [comment]
Removed Settings.set in the new test version https://developer.athom.com/apps/app/com.ubnt.unifiprotect/build/27
