### ISSUE TITLE
UDM-Pro failure

### ISSUE THREAD

**Issue by iFac3** [steffjenl/com.ubnt.unifiprotect#2]
Hi steffdjen,

Awesome app, thanks for working on this!

Issue with my setup is the following. When I try to add UDM-Pro to devices, I get this:

![IMG_5208](https://user-images.githubusercontent.com/51527573/80800906-0521ef80-8bab-11ea-8882-3eb0f73cc0b9.PNG)

**Comment by steffjenl** [comment]
Please set an controller name in the settings of Unifi Protect
![image](https://user-images.githubusercontent.com/2580852/80801036-6fd32b00-8bab-11ea-90af-5466591cb4de.png)

**Comment by iFac3** [comment]
I have name here:

<img width="737" alt="Képernyőfotó 2020-05-01 - 13 02 25" src="https://user-images.githubusercontent.com/51527573/80801319-3ea72a80-8bac-11ea-9ee4-c6b72d0a489a.png">

It's in the UDM advanced settings

**Comment by iFac3** [comment]
There is no screen in UDM-Protect web GUI what you posted... Wooow...

**Comment by iFac3** [comment]
Under UniFi Protect General, there is no option for naming, see below:

<img width="657" alt="Képernyőfotó 2020-05-01 - 13 48 45" src="https://user-images.githubusercontent.com/51527573/80803449-99dc1b80-8bb2-11ea-9a63-89866304462b.png">

**Comment by calamarcus** [comment]
Hi! I have the same problem. I have no option to set name in the unifi protect either.

**Comment by denniedegroot** [comment]
@steffjenl The issue is that you are calling api.getServer when you are not logged in yet. Then the error 'property name of null' occurs during pairing because the UDM-Pro is not found. I added a hacky delay (so the login is completed) and then the UDM-Pro is found.

(node:14576) UnhandledPromiseRejectionWarning: Error: Not logged in.
    at /lib/ufpapi.js:124:67
    at new Promise (<anonymous>)
    at UfPapi._get (/lib/ufpapi.js:122:12)
    at /lib/ufpapi.js:577:12
    at new Promise (<anonymous>)
    at UfPapi.getServer (/lib/ufpapi.js:576:12)
    at NvrDriver.onInit (/drivers/unifiprotect/driver.js:13:20)
    at /opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/Driver.js:1:3555
    at NvrDriver.__initDevices (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/Driver.js:1:1838)
    at NvrDriver.__onReady (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/Driver.js:1:3542)
(node:14576) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:14576) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by steffjenl** [comment]
> @steffjenl The issue is that you are calling api.getServer when you are not logged in yet. Then the error 'property name of null' occurs during pairing because the UDM-Pro is not found. I added a hacky delay (so the login is completed) and then the UDM-Pro is found.
> 
> (node:14576) UnhandledPromiseRejectionWarning: Error: Not logged in.
> at /lib/ufpapi.js:124:67
> at new Promise ()
> at UfPapi._get (/lib/ufpapi.js:122:12)
> at /lib/ufpapi.js:577:12
> at new Promise ()
> at UfPapi.getServer (/lib/ufpapi.js:576:12)
> at NvrDriver.onInit (/drivers/unifiprotect/driver.js:13:20)
> at /opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/Driver.js:1:3555
> at NvrDriver.__initDevices (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/Driver.js:1:1838)
> at NvrDriver.__onReady (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/Driver.js:1:3542)
> (node:14576) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
> (node:14576) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Can you try my new version on github on the develop branch?

I have moved the api.getServer to a place later then the login.

**Comment by denniedegroot** [comment]
Just tested it, the UDM-Pro is now found.

**Comment by steffjenl** [comment]
> Just tested it, the UDM-Pro is now found.

@denniedegroot can you also test for me the solution for #3 ? many thanks for it!

**Comment by iFac3** [comment]
I think it’s too early to close this issue...

...after a while this happens. It solves an app restart, but only for a while.

![IMG_0172](https://user-images.githubusercontent.com/51527573/80872034-c45fce80-8caf-11ea-8645-4e844862c6ae.png)

**Comment by calamarcus** [comment]
Same for me, the app crashes.

2 maj 2020 kl. 20:02 skrev iFac3 <notifications@github.com>:

﻿
I think it’s too early to close this issue...

...after a while this happens. It solves an app restart, but only for a while.

**Comment by steffjenl** [comment]
Please sideload the app and give me the error message. You can find an how to here https://community.athom.com/t/how-to-cli-install-method/198

before you do 'homey app run' please execute 'npm install' this will install all javascript packages in the project directory.

**Comment by steffjenl** [comment]
@calamarcus and @iFac3 i closed this issue because the .name error is solved. 
#3  is about the snaps.jpeg and it's probably the cause of the crash. In the meantime I have made a new one. Please continue in #3 .
