### ISSUE TITLE
Snapshots for G4 Doorbell wrong aspect ratio

### ISSUE THREAD

**Issue by denniedegroot** [steffjenl/com.ubnt.unifiprotect#20]
In the code I see that snapshots have a default of 1920px width. This gives a 16:9 picture.
The G4 doorbell however has a width of 1200px and a aspect ratio of 4:3

So when viewing the snapshot image in the Homey app or using the image token the picture resolution/aspect ratio for the G4 doorbell is not correct.

**Comment by steffjenl** [comment]
> In the code I see that snapshots have a default of 1920px width. This gives a 16:9 picture.
> The G4 doorbell however has a width of 1200px and a aspect ratio of 4:3
> 
> So when viewing the snapshot image in the Homey app or using the image token the picture resolution/aspect ratio for the G4 doorbell is not correct.

What is the type in the bootstrap endpoint from the Doorbell? UVC G4 Doorbell

**Comment by steffjenl** [comment]
I have created an test version for the name 'UVC G4 Doorbell'

https://homey.app/a/com.ubnt.unifiprotect/test/

**Comment by denniedegroot** [comment]
Thanks. But it doesn't work because the function ```getAspectRatioHeight(cameraId, widthInPixels)``` isn't synchronous. So it will return first ```return widthInPixels / 16 * 9``` and then later if the camera is found in the for loop ```return widthInPixels / 4 * 3```

**Comment by denniedegroot** [comment]
Fixed in latest version. Thanks!
