### ISSUE TITLE
Allow Unifi doorbell/cam to Google Home

### ISSUE THREAD

**Issue by mbnn** [steffjenl/com.ubnt.unifiprotect#23]
Hello,

Just wondering, but is it possible to expose the UniFi Protect cams/doorbell to the Google Home integration by Homey?
This way you could use the Google assistant/home for extra things like doorbell notifications.

**Comment by steffjenl** [comment]
@mbnn you can cast an image to your Google Home Hub!

![image](https://user-images.githubusercontent.com/2580852/108623982-39201700-7442-11eb-8fb3-611ac5c921cc.png)
