### ISSUE TITLE
Problem sending snapshot

### ISSUE THREAD

**Issue by ferrydl** [steffjenl/com.ubnt.unifiprotect#24]
I have a Dream Machine Pro and a G3 Pro camera. The app runs great. I have created a flow that when somebody presses the doorbell (a simple KAKU doorbell) that the G3 camera takes a snapshot and sends it to my phone as a push-notification.
I worked great until a couple of weeks ago. Either I don't recive a push-notification at all (App crashes) or there is no snapshot.
Any help is welcome.

**Comment by ralftar** [comment]
Snapshot not working for my CKP2 either

**Comment by steffjenl** [comment]
Is this fixed in the last release?

**Comment by ferrydl** [comment]
Yes, it is! Thanks

Op wo 9 mrt. 2022 07:57 schreef steffjenl ***@***.***>:
