### ISSUE TITLE
camera’s recording mode cannot be set anymore

### ISSUE THREAD

**Issue by cjvs** [steffjenl/com.ubnt.unifiprotect#25]
I cannot set the recording mode of the camera's anymore.
Unifi protect app version 1.3.1
Homey version 6.0.0-rc.5

A test flow to change the recording mode of the camera runs without error. However, recording mode does not change. Checked it on two different camera's. Neither works.

**Comment by steffjenl** [comment]
Fixed in version 1.5.8
