### ISSUE TITLE
Snapshot idea

### ISSUE THREAD

**Issue by iFac3** [steffjenl/com.ubnt.unifiprotect#3]
Hi again,

I think this UniFi OS cookie issue could be workarounded. :)

A setup option at each and every camera would be needed, where the direct or NVR anonymus snapshot image url could be set. (After enabling it in the camera web GUI)

**Comment by steffjenl** [comment]
Do you know how to get an json message from the server? and do you have an screenshot from the settings page with the option? (anonymus snapshot image url in web gui).

**Comment by iFac3** [comment]
After you logging into the specific camera, with "ubnt" user name and device password from here:

<img width="559" alt="Képernyőfotó 2020-05-01 - 13 52 09" src="https://user-images.githubusercontent.com/51527573/80803573-fd664900-8bb2-11ea-898e-5180237f727a.png">

You can enable Anonymous Snapshot here:

<img width="867" alt="Képernyőfotó 2020-05-01 - 13 47 21" src="https://user-images.githubusercontent.com/51527573/80803638-37374f80-8bb3-11ea-83a3-07ba4373f610.png">


Then you can get the snapshot with url: 'http://jour.device.ip.address/snap.jpeg'.

**Comment by iFac3** [comment]
Btw... you can add to the supported device list [UVC-G3-MICRO](https://www.ui.com/unifi-video/unifi-video-camera-g3-micro/), I have two, can confirm that works with your app.

**Comment by calamarcus** [comment]
Uvc-g3-micro works for me too

**Comment by steffjenl** [comment]
> Hi again,
> 
> I think this UniFi OS cookie issue could be workarounded. :)
> 
> A setup option at each and every camera would be needed, where the direct or NVR anonymus snapshot image url could be set. (After enabling it in the camera web GUI)

Thanks for this solution, unfortunately this solution is not very user-friendly.

Not every Homey user is extremely technical.

But maybe this is a solution if someone wants a url for a snapshot flow for an external application.

**Comment by iFac3** [comment]
Anyway, thanks for considering this!

(However much easily doable, than the advised docker solution, isn’t it?)

Rgds,

Gergely.

**Comment by steffjenl** [comment]
> Anyway, thanks for considering this! (However much easily doable, than the advised docker solution, isn’t it?) Rgds, Gergely.
> […](#)
> On 2020. May 2. 11:16 +0200, steffjenl ***@***.***>, wrote: > Hi again, > I think this UniFi OS cookie issue could be workarounded. :) > A setup option at each and every camera would be needed, where the direct or NVR anonymus snapshot image url could be set. (After enabling it in the camera web GUI) Thanks for this solution, unfortunately this solution is not very user-friendly. Not every Homey user is extremely technical. But maybe this is a solution if someone wants a url for a snapshot flow for an external application. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.


The docker solution was certainly not a nice one. I'm actually looking for something much more user-friendly, but I don't have a UDM or any other device with Unifi OS.

**Comment by steffjenl** [comment]
> Anyway, thanks for considering this! (However much easily doable, than the advised docker solution, isn’t it?) Rgds, Gergely.
> […](#)
> On 2020. May 2. 11:16 +0200, steffjenl ***@***.***>, wrote: > Hi again, > I think this UniFi OS cookie issue could be workarounded. :) > A setup option at each and every camera would be needed, where the direct or NVR anonymus snapshot image url could be set. (After enabling it in the camera web GUI) Thanks for this solution, unfortunately this solution is not very user-friendly. Not every Homey user is extremely technical. But maybe this is a solution if someone wants a url for a snapshot flow for an external application. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

Do you know how to side-load an Homey app? Would you like to test the latest version from GitHub? It now contains the snapshot.jpeg solution.

Once this has been tested I will release a new version for the other Homey users.

**Comment by iFac3** [comment]
I was betatesting the Philips Air app for long time. The developer just sent me a link that led to Homey App store and I was able to install the beta version of his work before final release.

How can I install your app from github?

Üdv,

G.

**Comment by steffjenl** [comment]
> I was betatesting the Philips Air app for long time. The developer just sent me a link that led to Homey App store and I was able to install the beta version of his work before final release. How can I install your app from github? Üdv, G.
> […](#)
> On 2020. May 2. 13:58 +0200, steffjenl ***@***.***>, wrote: > Anyway, thanks for considering this! (However much easily doable, than the advised docker solution, isn’t it?) Rgds, Gergely. > … > On 2020. May 2. 11:16 +0200, steffjenl @.***>, wrote: > Hi again, > I think this UniFi OS cookie issue could be workarounded. :) > A setup option at each and every camera would be needed, where the direct or NVR anonymus snapshot image url could be set. (After enabling it in the camera web GUI) Thanks for this solution, unfortunately this solution is not very user-friendly. Not every Homey user is extremely technical. But maybe this is a solution if someone wants a url for a snapshot flow for an external application. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Do you know how to side-load an Homey app? Would you like to test the latest version from GitHub? It now contains the snapshot.jpeg solution. Once this has been tested I will release a new version for the other Homey users. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

You can use https://homey.app/a/com.ubnt.unifiprotect/test/ for beta testing

**Comment by iFac3** [comment]
Remarks:

The installation process seemed for mee too long on my Homey Pro. It took approx 90-120 seconds while the led ring was running around, I’ve never installed this long any other app. You can say, if it’s okay or there is something behind this.

Adding UDM-Pro was successful during firs attempt. However there is no info on storage yet, after 10 minutes.

![IMG_0169](https://user-images.githubusercontent.com/51527573/80864473-31a93a80-8c83-11ea-8f45-a07b5e21bbad.jpeg)


Homey app freezed when I added cameras, but I’m betatesting iPad Homey app, so do not take it serious. Cameras have been already added when I reopened the app, but there was no snapshot nor details. I removed cameras, then readded. There are no details after 15 minutes, see below:

![IMG_0167](https://user-images.githubusercontent.com/51527573/80864554-b1cfa000-8c83-11ea-8cad-bcf8536835ed.jpeg)
![IMG_0168](https://user-images.githubusercontent.com/51527573/80864555-b6945400-8c83-11ea-9b6f-f8941abc951b.jpeg)

**Comment by iFac3** [comment]
Checked motion alerts, does not report motions to Homey what Protect itself registers.

**Comment by iFac3** [comment]
Without any change, it has started to report motions on all the three cameras I have.

Question: Sensitivity should be adjusted in Protect, am I right?

**Comment by steffjenl** [comment]
> Without any change, it has started to report motions on all the three cameras I have. (Still no info on storage at UDM-Pro)
> 
> Question: Sensitivity should be adjusted in Protect, am I right?

Yes that is correct!

**Comment by steffjenl** [comment]
> Without any change, it has started to report motions on all the three cameras I have. (Still no info on storage at UDM-Pro)
> 
> Question: Sensitivity should be adjusted in Protect, am I right?

> (Still no info on storage at UDM-Pro

That's right! UDM does not release storage information through the API. If you know how to get this information through an API I'd love to hear it!

**Comment by steffjenl** [comment]
I published a new version through GitHub. And as a test app via Homey https://homey.app/a/com.ubnt.unifiprotect/test/

Only when you start the app via side-load you will see the error messages and I can investigate this better.

As I mentioned earlier I don't have a UnifiOS device and I have to solve and test it based on information from you.

It works well on a Cloud Key Gen2 Pro.

**Side-load howto:**
https://community.athom.com/t/how-to-cli-install-method/198

before you do 'homey app run' please execute 'npm install' this will install all javascript packages in the project directory.

**Comment by denniedegroot** [comment]
@steffjenl I am currently testing the new version. The action flowcard 'create a snapshot' doesn't seem to work and creates an empty image when I check it in  http://developer.athom.com/tools/images.

**Comment by denniedegroot** [comment]
I had the following idea to make the snapshot easier. Can't you refresh the snapshot image on motion and set the Homey image url as the snapshot url? Or maybe create a 'action card' to force a refresh? Then you don't need to check the 'anonymous snapshot' setting because the snapshot url is from Homey.

**Comment by steffjenl** [comment]
> @steffjenl I am currently testing the new version. The action flowcard 'create a snapshot' doesn't seem to work and creates an empty image when I check it in http://developer.athom.com/tools/images.

Thanks, I found the bug that caused the image to be empty. I have also found and fixed the memory leak in the latest version on github and am now using homey's cloudUrl. So you no longer need to activate anonymous snapshot url.

**Comment by denniedegroot** [comment]
@steffjenl great work! I tested it and it seems to work quite nicely. I did find a other bug, when you press the 'refresh' button in the Homey app the snapshot image isn't actually refreshed to the current snapshot image but rather a cached image?

**Comment by iFac3** [comment]
Sorry, but I was pretty busy in the mean time...

..however I installed 1.0.9 which still crashes at me time by time. Is there a newer version?

**Comment by steffjenl** [comment]
We are on version 1.1.2 (sorry everytime i test an version i must bump the version).

https://homey.app/a/com.ubnt.unifiprotect/test/

i found some memoryleaks an the cloud-key as device in the app is deprecated. You can only add camera's and not the nvr anymore!

UnifiOS has removed all details from the NVR in the API and this cost lots of extra memory.

**Comment by steffjenl** [comment]
> @steffjenl great work! I tested it and it seems to work quite nicely. I did find a other bug, when you press the 'refresh' button in the Homey app the snapshot image isn't actually refreshed to the current snapshot image but rather a cached image?

@denniedegroot in version 1.2.0 (https://homey.app/a/com.ubnt.unifiprotect/test/) i have added an timestamp in the url from the snapshot. I think this will help to get the latest snapshot.

**Comment by denniedegroot** [comment]
@steffjenl I just tested it but the snapshot isn't refreshing when pressing the refresh button. It seems the image is refreshed every 10 seconds or so.

**Comment by steffjenl** [comment]
That’s correct! Limitation of the software from UniFi.

Verstuurd vanaf mijn iPhone

Op 9 mei 2020 om 20:06 heeft denniedegroot <notifications@github.com> het volgende geschreven:

﻿

@steffjenl<https://github.com/steffjenl> I just tested it but the snapshot isn't refreshing when pressing the refresh button. It seems the image is refreshed every 10 seconds or so.
