### ISSUE TITLE
App crashes, a pause symbol is on the app and nothing runs before restarting the app

### ISSUE THREAD

**Issue by Krisstenswe** [steffjenl/com.ubnt.unifiprotect#33]
The app has been working until 2-3 weeks ago.
Now the app crashes. A pause symbol is on the app and nothing runs before I restart the app. It then runs for 5-10 minutes, sometimes for an hour or so.
I see that this is reported as a common issue on the community.

**Comment by Krisstenswe** [comment]
Diagnostic report: edab0ce7-293f-4420-926d-cf3d2ca1d07f

**Comment by Krisstenswe** [comment]
[Debug info.txt](https://github.com/steffjenl/com.ubnt.unifiprotect/files/7803164/Debug.info.txt)

**Comment by steffjenl** [comment]
Fixed in #34
