### ISSUE TITLE
error : socket.on is not  a function

### ISSUE THREAD

**Issue by skynett81** [steffjenl/com.ubnt.unifiprotect#38]
Hi . i have a problem when tryning to add cams to the unifi protect app on homey.
i have sett the host,username,password and port.  The error is:  socket.on is not a function

i have udm pro and homey pro

**Comment by whysogit** [comment]
I get the same when trying to add cams.
Connecting to the UDMP seems to work.

**Comment by steffjenl** [comment]
You can download the test version on https://homey.app/a/com.ubnt.unifiprotect/test/

**Comment by skynett81** [comment]
that did work , but it did not find my G4 Doorbell .

**Comment by whysogit** [comment]
> that did work , but it did not find my G4 Doorbell .

Same for me. All cameras work except the doorbell.

**Comment by whysogit** [comment]
Doorbell working now with version 1.5.6

**Comment by skynett81** [comment]
there is still an error , the app needs restarting often for the cams to work .
