### ISSUE TITLE
V1.5.6 keep dropping cameras

### ISSUE THREAD

**Issue by yhaugom** [steffjenl/com.ubnt.unifiprotect#41]
After a while (some hours), the camera devices is lost.
![image](https://user-images.githubusercontent.com/1016457/152670259-e91d51c3-3759-4f5b-be85-5d3ebc52e89c.png)

Restart of the app within the Homey app fixes it temporarily.

Diagnostics report reference: 1781b325-0d13-4982-9f6e-c628ee304baa

**Comment by whysogit** [comment]
Same for me.

16e71094-5c68-4763-aa56-ebad5a709db2

**Comment by bbruggers** [comment]
Same problem here.

**Comment by whysogit** [comment]
Seems to work after latest update (1.5.7)

**Comment by yhaugom** [comment]
Yes, seems to be stable, but now the motion alerts won't trigger anymore.

**Comment by yhaugom** [comment]
Ok, then I might have to do some kind of reconnect. Will try.
