### ISSUE TITLE
Can no longer set the cameras to ‘Record only motion’ via a flow

### ISSUE THREAD

**Issue by Krisstenswe** [steffjenl/com.ubnt.unifiprotect#42]
Since update to 1.5.4 I can no longer set the cameras to ‘Record only motion’ via a flow.
When I set the recording status of a camera via a flow to ‘Record only motion’ nothing happens.
Set other recording modes work fine.

**Comment by theguide1234** [comment]
Same issue here. On Saturday afternoon I noticed my Unifi protect got updated to 1.5.6 and did a quick check and saw the ‘Opnamemodus’ displayed correcty as ‘Detections’. Didn’t have a lot of time so checked this afternoon and notice I’m on 1.5.7 but unfortunately the ‘Opnamemodus’ is ‘-’ again.

**Comment by steffjenl** [comment]
Unifi changed recording mode Motion to Detections in the API in the next release this is fixed.

**Comment by steffjenl** [comment]
#25 maybe the same?

**Comment by steffjenl** [comment]
Fixed in version 1.5.8
