### ISSUE TITLE
Smart detection doesn't work

### ISSUE THREAD

**Issue by Tipmanfrank** [steffjenl/com.ubnt.unifiprotect#43]
A simple flow: IF smart detection THEN send push message is not working.
Do I need more parameters? Does app not work for smart detection.

**Comment by yhaugom** [comment]
Worked on earlier version for me. But not from V1.5.7.

**Comment by Tipmanfrank** [comment]
Yes. For me too. But it doesnt from 1.5.6 

So sad that it doesn’t work correct anymore. 

Venlig hilsen

Frank Larsen

**Comment by steffjenl** [comment]
Fixed in version 1.5.8
