### ISSUE TITLE
Add support for G4 Doorbell

### ISSUE THREAD

**Issue by mbnn** [steffjenl/com.ubnt.unifiprotect#6]
Hello there,

It would be really nice if the G4 Doorbell would be added to this plugin.
It works by default, however push notifications for when someone presses a doorbell would be extremely usefull.

Thank you.

**Comment by steffjenl** [comment]
When you can send an G4 Doorbell we can try to add support for it. Because you can’t buy it in an normal store we must wait when it is released.

**Comment by marcelvenema** [comment]
Hi Stephan and Jeroen, 
Great work! Homebridge has support for the G4 Doorbell. Here is the link to the source code, maybe it helps.
https://github.com/hjdhjd/homebridge-unifi-protect

**Comment by steffjenl** [comment]
When the doorbell is released in The Netherlands I will buy one. Without I can’t test the integration

**Comment by mrmannetje** [comment]
+1
Would love to have g4 doorbell support. I see it’s scheduled at this local shop for February 7th 2021. https://ubntsupply.nl/producten/719-unifi-protect-g4-doorbell.html

Def willing to chip in a few donation beers when done.

**Comment by steffjenl** [comment]
@mrmannetje can you contact me by e-mail? are you dutch?

**Comment by mrmannetje** [comment]
> @mrmannetje can you contact me by e-mail? are you dutch?

Yep, Dutch and no problem to contact you by email. But where do I find you email address :-)

**Comment by steffjenl** [comment]
@mrmannetje  or @mbnn  can one of you contact me on my email address stephan@monkeysoft.nl ? I want to look with you on your controller and see the output from some endpoints.

**Comment by steffjenl** [comment]
You can download a test version with support for doorbell on https://homey.app/a/com.ubnt.unifiprotect/test/

**Comment by mbnn** [comment]
Sounds good, en zal best werken, maar moet ff w8ten voor ik mijn unifi g4 doorbell weer heb :) Had mijn huis verkocht met deurbel erbij en heb nu een nieuwe vanuit de US over laten komen, nog paar dagen dan kan ik weer testen. Thanks!

**Comment by steffjenl** [comment]
> Sounds good, en zal best werken, maar moet ff w8ten voor ik mijn unifi g4 doorbell weer heb :) Had mijn huis verkocht met deurbel erbij en heb nu een nieuwe vanuit de US over laten komen, nog paar dagen dan kan ik weer testen. Thanks!

Wat zijn de kosten om hem over te halen? en via welke post bedrijf heb je dat geregeld? Misschien toch maar één vanuit de US laten komen. Duurt wel erg lang allemaal.

**Comment by mbnn** [comment]
Via viabox.com maar heb em nog niet gekregen duurt best lang en komt een 100$ ongeveer bij alles bij elkaar. Tja je moet wat he 😛

**Comment by steffjenl** [comment]
In next version the doorbell support is added.

**Comment by denniedegroot** [comment]
@steffjenl via https://www.bhphotovideo.com/ kun je hem ook kopen, heb ik zelf ook gedaan. Totaal ongeveer €220 incl. douane en belastingen!

**Comment by mbnn** [comment]
Cool, when will this be pushed to the appstore of homey? :)

**Comment by mbnn** [comment]
Inmiddels deurbel binnen, het werkt en als op de deurbel gedrukt word kan ik via een flow bijv sonos speakers iets laten afspelen, maar de flow stopt automatisch iedere keer omdat deze te vaak werd uitgevoerd. Volgens mij denkt ie dat deurbel ingedrukt blijft ofzo?

**Comment by steffjenl** [comment]
> Inmiddels deurbel binnen, het werkt en als op de deurbel gedrukt word kan ik via een flow bijv sonos speakers iets laten afspelen, maar de flow stopt automatisch iedere keer omdat deze te vaak werd uitgevoerd. Volgens mij denkt ie dat deurbel ingedrukt blijft ofzo?

Kan je de flow sturen die je gebruikt ?

**Comment by mbnn** [comment]
https://homey.app/f/mznZsu

Bij deze.

**Comment by mbnn** [comment]
This problem is still there fyi, when using the flowcard 'deurbel rinkelt' it goes in a loop for some strange reason.
