### ISSUE TITLE
New reverse engineering

### ISSUE THREAD

**Issue by iFac3** [steffjenl/com.ubnt.unifiprotect#8]
Have you cought this:

“For the more technically inclined - this plugin has continued to pioneer the HomeKit user experience for UniFi Protect by being the first Homebridge plugin to successfully reverse engineer the UniFi Protect realtime events API that was introduced with UniFi OS. This means that rather than poll the controller every few seconds to catch events, we're able to capture motion and doorbell ring events in realtime, providing an extremely responsive HomeKit experience, and reducing the performance impact to Protect controllers.”

More info: https://github.com/hjdhjd/homebridge-unifi-protect

It would be very awesome, if G4 doorbell could make Homey speak.

**Comment by steffjenl** [comment]
First test version with realtime events in build in our test version

https://homey.app/a/com.ubnt.unifiprotect/test/

**Comment by steffjenl** [comment]
Next version will be with real time updates and doorbell support.
