### ISSUE TITLE
Bug in camera 

### ISSUE THREAD

**Issue by PatrickSassenheim** [steffjenl/com.ubnt.unifiprotect#9]
There is a problem with one of the added camera's. Is has no image and also not the camera tap in the buttom of the lay-out.
The other camera works great and it are two the same camera's with the same settings.
![IMG_9851](https://user-images.githubusercontent.com/72101004/94601686-2428c880-0294-11eb-8d20-61fe981f525c.jpg)
![IMG_9852](https://user-images.githubusercontent.com/72101004/94601690-25f28c00-0294-11eb-900c-a828a5a67033.jpg)

**Comment by steffjenl** [comment]
And when you restarted the app or homey ?

**Comment by PatrickSassenheim** [comment]
I have restarted the app a few times and delete the Protect app and installed it another time and the same issue.

I have done this setup with 4 camera's already at my friends house and no issues.

I have disconnect the whole system right now because from beginning oktober the construction in our house will be done and this will take till half November.
The system will be online at the half of November so I can check it when everything is online again.

Really great that you react so fast!!

**Comment by steffjenl** [comment]
Hello Patrick, how is your construction? and how is the connection the the Homey App and your camera's ?

**Comment by PatrickSassenheim** [comment]
Hi Steffen,

It works at the moment. Sometimes after a long time I need to restart the Protect App on the homey.

**Comment by steffjenl** [comment]
This is fixt in next version!
